### ISSUE TITLE
Allow empty value.

### ISSUE THREAD

**Issue by hbatalhaStch** [cedvdb/flutter_country_selector#14]
I just had a case where the  phone I got from a database didn't contain a country code and I got an exception from [this package](https://github.com/cedvdb/phone_numbers_parser) that says that the country code was not found and it just crashed.

**Comment by cedvdb** [comment]
missing:

  - sample
  - expected behavior

**Comment by hbatalhaStch** [comment]
move to https://github.com/cedvdb/phone_numbers_parser/issues/67
