### ISSUE TITLE
Can't access CountrySelectorLocalization.countryName(isoCode)

### ISSUE THREAD

**Issue by aggeloskoutanis** [cedvdb/flutter_country_selector#8]
Hello there. I am trying to access  CountrySelectorLocalization.countryName(isoCode) as it's described on the home page of this repository. Still, it looks like a method with the name countryName is not accessible from this class.

**Comment by cedvdb** [comment]
Use `CountrySelectorLocalization.of(context)?.countryName(isoCode)`
