### ISSUE TITLE
Wrong wording in greek localization

### ISSUE THREAD

**Issue by aggeloskoutanis** [cedvdb/flutter_country_selector#9]
In class `CountrySelectorLocalizationEl` and specifically in line 18 stands this: `return 'Επιλέγω $country';`. The correct one in Greek is "Επίλεξε" instead of "Επιλέγω".

**Comment by cedvdb** [comment]
Please submit a PR with the required changes

**Comment by cedvdb** [comment]
fixed in 1.0.8
